version: '3.8'


services:
  eda-playground-broker:
    container_name: eda-playground-broker
    image: dleclercpro/eda-playground-broker:v2.0.0
    build:
      context: ./Apps
      dockerfile: Broker.Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./Apps/Broker/public:/apps/Broker/public # Client app for now
    environment:
      NODE_ENV: production

  eda-playground-order:
    container_name: eda-playground-order
    image: dleclercpro/eda-playground-order:v2.0.0
    build:
      context: ./Apps
      dockerfile: Order.Dockerfile
    depends_on:
      - eda-playground-broker
    environment:
      NODE_ENV: production

  eda-playground-payment:
    container_name: eda-playground-payment
    image: dleclercpro/eda-playground-payment:v2.0.0
    build:
      context: ./Apps
      dockerfile: Payment.Dockerfile
    depends_on:
      - eda-playground-broker
    environment:
      NODE_ENV: production

  eda-playground-delivery:
    container_name: eda-playground-delivery
    image: dleclercpro/eda-playground-delivery:v2.0.0
    build:
      context: ./Apps
      dockerfile: Delivery.Dockerfile
    depends_on:
      - eda-playground-broker
    environment:
      NODE_ENV: production

  eda-playground-prometheus:
    container_name: eda-playground-prometheus
    image: dleclercpro/eda-playground-prometheus:v2.0.0
    build:
      context: ./Apps
      dockerfile: Prometheus.Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - eda-playground-node-exporter
      - eda-playground-cadvisor

  eda-playground-grafana:
    container_name: eda-playground-grafana
    image: dleclercpro/eda-playground-grafana:v2.0.0
    build:
      context: ./Apps
      dockerfile: Grafana.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - eda-playground-prometheus

  eda-playground-node-exporter:
    container_name: eda-playground-node-exporter
    image: prom/node-exporter
    ports:
      - 9100:9100

  eda-playground-cadvisor:
    container_name: eda-playground-cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.1 # M1/M2 Mac
    platform: linux/aarch64 # M1/M2 Mac
    privileged: true # Stops OOM warning
    ports:
      - 8080:8080
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro