version: '3.8'

services:
  broker:
    container_name: broker-app
    image: dleclercpro/eda-playground-broker:latest
    build:
      context: ./Apps
      dockerfile: Broker.Dockerfile
    ports:
      - 4000:4000
    networks:
      - app
    environment:
      NODE_ENV: production

  order:
    container_name: order-app
    image: dleclercpro/eda-playground-order:latest
    build:
      context: ./Apps
      dockerfile: Order.Dockerfile
    networks:
      - app
    depends_on:
      - broker
    environment:
      NODE_ENV: production

  payment:
    container_name: payment-app
    image: dleclercpro/eda-playground-payment:latest
    build:
      context: ./Apps
      dockerfile: Payment.Dockerfile
    networks:
      - app
    depends_on:
      - broker
    environment:
      NODE_ENV: production

  delivery:
    container_name: delivery-app
    image: dleclercpro/eda-playground-delivery:latest
    build:
      context: ./Apps
      dockerfile: Delivery.Dockerfile
    networks:
      - app
    depends_on:
      - broker
    environment:
      NODE_ENV: production

networks:
  app:
    driver: bridge