version: '3.8'

services:
  broker:
    container_name: broker-app
    stop_grace_period: 1s # SIGKILL after 1s
    image: eda-playground/broker
    build:
      context: ./Apps
      dockerfile: Broker.Dockerfile
    ports:
      - 4000:4000
    networks:
      - app
    environment:
      NODE_ENV: production

  order:
    container_name: order-app
    stop_grace_period: 1s # SIGKILL after 1s
    image: eda-playground/order
    build:
      context: ./Apps
      dockerfile: Order.Dockerfile
    networks:
      - app
    depends_on:
      - broker
    environment:
      NODE_ENV: production

  payment:
    container_name: payment-app
    stop_grace_period: 1s # SIGKILL after 1s
    image: eda-playground/payment
    build:
      context: ./Apps
      dockerfile: Payment.Dockerfile
    networks:
      - app
    depends_on:
      - broker
    environment:
      NODE_ENV: production

  delivery:
    container_name: delivery-app
    stop_grace_period: 1s # SIGKILL after 1s
    image: eda-playground/delivery
    build:
      context: ./Apps
      dockerfile: Delivery.Dockerfile
    networks:
      - app
    depends_on:
      - broker
    environment:
      NODE_ENV: production

networks:
  app:
    driver: bridge