version: '3.8'


services:
  sweets-nginx:
    container_name: sweets-nginx
    image: dleclercpro/reverse-proxy:latest
    restart: always
    ports:
      - 443:443 # HTTPS
      - 80:80   # HTTP
    networks:
      - custom
    volumes:
      - letsencrypt:/etc/letsencrypt # Keep SSL certificates
    depends_on:
      - sweets-broker
    env_file:
      - .env

  sweets-broker:
    container_name: sweets-broker
    image: dleclercpro/sweets-broker:latest
    build:
      context: ./Apps
      dockerfile: Broker.Dockerfile
    networks:
      - custom
    volumes:
      - ./Apps/Broker/public:/apps/Broker/public # Client app for now
    environment:
      NODE_ENV: production

  sweets-order:
    container_name: sweets-order
    image: dleclercpro/sweets-order:latest
    build:
      context: ./Apps
      dockerfile: Order.Dockerfile
    networks:
      - custom
    depends_on:
      - sweets-broker
    environment:
      NODE_ENV: production

  sweets-payment:
    container_name: sweets-payment
    image: dleclercpro/sweets-payment:latest
    build:
      context: ./Apps
      dockerfile: Payment.Dockerfile
    networks:
      - custom
    depends_on:
      - sweets-broker
    environment:
      NODE_ENV: production

  sweets-delivery:
    container_name: sweets-delivery
    image: dleclercpro/sweets-delivery:latest
    build:
      context: ./Apps
      dockerfile: Delivery.Dockerfile
    networks:
      - custom
    depends_on:
      - sweets-broker
    environment:
      NODE_ENV: production

  sweets-prometheus:
    container_name: sweets-prometheus
    image: dleclercpro/sweets-prometheus:latest
    build:
      context: ./Apps
      dockerfile: Prometheus.Dockerfile
    networks:
      - custom
    depends_on:
      - sweets-node-exporter
      - sweets-cadvisor

  sweets-grafana:
    container_name: sweets-grafana
    image: dleclercpro/sweets-grafana:latest
    build:
      context: ./Apps
      dockerfile: Grafana.Dockerfile
    networks:
      - custom
    depends_on:
      - sweets-prometheus

  sweets-node-exporter:
    container_name: sweets-node-exporter
    image: prom/node-exporter
    networks:
      - custom

  sweets-cadvisor:
    container_name: sweets-cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.1 # M1/M2 Mac
    platform: linux/aarch64 # M1/M2 Mac
    privileged: true # Stops OOM warning
    networks:
      - custom
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro


volumes:
  letsencrypt:


networks:
  # Custom network to communicate with external services/containers
  custom:
    external: true