version: '3.8'


services:
  sweets-broker:
    container_name: sweets-broker
    image: dleclercpro/sweets-broker:v2.1.0
    build:
      context: ./Apps
      dockerfile: Broker.Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./Apps/Broker/public:/apps/Broker/public # Client app for now
    environment:
      NODE_ENV: production

  sweets-order:
    container_name: sweets-order
    image: dleclercpro/sweets-order:v2.1.0
    build:
      context: ./Apps
      dockerfile: Order.Dockerfile
    depends_on:
      - sweets-broker
    environment:
      NODE_ENV: production

  sweets-payment:
    container_name: sweets-payment
    image: dleclercpro/sweets-payment:v2.1.0
    build:
      context: ./Apps
      dockerfile: Payment.Dockerfile
    depends_on:
      - sweets-broker
    environment:
      NODE_ENV: production

  sweets-delivery:
    container_name: sweets-delivery
    image: dleclercpro/sweets-delivery:v2.1.0
    build:
      context: ./Apps
      dockerfile: Delivery.Dockerfile
    depends_on:
      - sweets-broker
    environment:
      NODE_ENV: production

  sweets-prometheus:
    container_name: sweets-prometheus
    image: dleclercpro/sweets-prometheus:v2.1.0
    build:
      context: ./Apps
      dockerfile: Prometheus.Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - sweets-node-exporter
      - sweets-cadvisor

  sweets-grafana:
    container_name: sweets-grafana
    image: dleclercpro/sweets-grafana:v2.1.0
    build:
      context: ./Apps
      dockerfile: Grafana.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - sweets-prometheus

  sweets-node-exporter:
    container_name: sweets-node-exporter
    image: prom/node-exporter
    ports:
      - 9100:9100

  sweets-cadvisor:
    container_name: sweets-cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.1 # M1/M2 Mac
    platform: linux/aarch64 # M1/M2 Mac
    privileged: true # Stops OOM warning
    ports:
      - 8080:8080
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro