version: '3.8'

services:
  broker:
    container_name: broker-app
    image: dleclercpro/eda-playground-broker:monitoring
    build:
      context: ./Apps
      dockerfile: Broker.Dockerfile
    ports:
      - 8080:80
    networks:
      - app
    depends_on:
      - monitor
    environment:
      NODE_ENV: production

  order:
    container_name: order-app
    image: dleclercpro/eda-playground-order:monitoring
    build:
      context: ./Apps
      dockerfile: Order.Dockerfile
    networks:
      - app
    depends_on:
      - broker
    environment:
      NODE_ENV: production

  payment:
    container_name: payment-app
    image: dleclercpro/eda-playground-payment:monitoring
    build:
      context: ./Apps
      dockerfile: Payment.Dockerfile
    networks:
      - app
    depends_on:
      - broker
    environment:
      NODE_ENV: production

  delivery:
    container_name: delivery-app
    image: dleclercpro/eda-playground-delivery:monitoring
    build:
      context: ./Apps
      dockerfile: Delivery.Dockerfile
    networks:
      - app
    depends_on:
      - broker
    environment:
      NODE_ENV: production

  monitor:
    container_name: monitor-app
    image: dleclercpro/eda-playground-monitor:monitoring
    build:
      context: ./Apps
      dockerfile: Monitor.Dockerfile
    ports:
      - 9090:9090
    networks:
      - app

  node-exporter:
    container_name: node-exporter-app
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - app

networks:
  app:
    driver: bridge