version: '3.8'


services:
  eda-playground-nginx:
    container_name: eda-playground-nginx
    image: dleclercpro/ssl-reverse-proxy:wss
    restart: always
    ports:
      - 443:443 # HTTPS
      - 80:80   # HTTP
    networks:
      - custom
    volumes:
      - letsencrypt:/etc/letsencrypt # Keep SSL certificates
    depends_on:
      - eda-playground-broker
    env_file:
      - .env

  eda-playground-broker:
    container_name: eda-playground-broker
    image: dleclercpro/eda-playground-broker:pretty-frontend
    build:
      context: ./Apps
      dockerfile: Broker.Dockerfile
    networks:
      - custom
    environment:
      NODE_ENV: production

  eda-playground-order:
    container_name: eda-playground-order
    image: dleclercpro/eda-playground-order:pretty-frontend
    build:
      context: ./Apps
      dockerfile: Order.Dockerfile
    networks:
      - custom
    depends_on:
      - eda-playground-broker
    environment:
      NODE_ENV: production

  eda-playground-payment:
    container_name: eda-playground-payment
    image: dleclercpro/eda-playground-payment:pretty-frontend
    build:
      context: ./Apps
      dockerfile: Payment.Dockerfile
    networks:
      - custom
    depends_on:
      - eda-playground-broker
    environment:
      NODE_ENV: production

  eda-playground-delivery:
    container_name: eda-playground-delivery
    image: dleclercpro/eda-playground-delivery:pretty-frontend
    build:
      context: ./Apps
      dockerfile: Delivery.Dockerfile
    networks:
      - custom
    depends_on:
      - eda-playground-broker
    environment:
      NODE_ENV: production

  eda-playground-prometheus:
    container_name: eda-playground-prometheus
    image: dleclercpro/eda-playground-prometheus:pretty-frontend
    build:
      context: ./Apps
      dockerfile: Prometheus.Dockerfile
    networks:
      - custom
    depends_on:
      - eda-playground-node-exporter
      - eda-playground-cadvisor

  eda-playground-grafana:
    container_name: eda-playground-grafana
    image: dleclercpro/eda-playground-grafana:pretty-frontend
    build:
      context: ./Apps
      dockerfile: Grafana.Dockerfile
    networks:
      - custom
    depends_on:
      - eda-playground-prometheus

  eda-playground-node-exporter:
    container_name: eda-playground-node-exporter
    image: prom/node-exporter
    networks:
      - custom

  eda-playground-cadvisor:
    container_name: eda-playground-cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.1 # M1/M2 Mac
    platform: linux/aarch64 # M1/M2 Mac
    privileged: true # Stops OOM warning
    networks:
      - custom
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro


volumes:
  letsencrypt:


networks:
  # Custom network to communicate with external services/containers
  custom:
    external: true