apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: monitoring


spec:
  selector:
    matchLabels:
      app: cadvisor
  
  # Pod
  template:
    metadata:
      labels:
        app: cadvisor
    
    spec:
      hostNetwork: true # Enable cAdvisor to access container network namespaces on host
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.47.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock