apiVersion: apps/v1
kind: DaemonSet


metadata:
  namespace: monitoring
  name: cadvisor


spec:
  selector:
    matchLabels:
      name: cadvisor
  
  # Pod
  template:
    metadata:
      labels:
        name: cadvisor
    
    spec:
      containers:
      - name: cadvisor
        image: gcr.io/cadvisor/cadvisor:v0.47.1 # M1/M2 Mac
        ports:
        - containerPort: 8080