apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring


spec:
  selector:
    matchLabels:
      name: node-exporter
  
  # Pod
  template:
    metadata:
      labels:
        name: node-exporter
    
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100