apiVersion: v1
kind: Service


metadata:
  name: broker # Use this as hostname to communicate with service via HTTP


spec:
  selector:
    name: broker
  ports:
    - protocol: TCP
      port: 80
      targetPort: broker-port