apiVersion: v1
kind: Service


metadata:
  namespace: monitoring
  name: cadvisor


spec:
  type: NodePort
  selector:
    name: cadvisor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080