apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring


spec:
  type: NodePort
  selector:
    name: cadvisor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080