apiVersion: v1
kind: Service
metadata:
  name: delivery # Use this as hostname to communicate with service via HTTP


spec:
  selector:
    app: delivery
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 80
    # Sidecar: container metrics exposure
    - name: cadvisor
      protocol: TCP
      port: 8080
      targetPort: 8080