apiVersion: v1
kind: Service


metadata:
  name: delivery # Use this as hostname to communicate with service via HTTP


spec:
  selector:
    name: delivery
  ports:
    - protocol: TCP
      port: 80
      targetPort: delivery-port