apiVersion: v1
kind: Service


metadata:
  namespace: monitoring
  name: grafana # Use this as hostname to communicate with service via HTTP


spec:
  type: NodePort
  selector:
    name: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: grafana-port