apiVersion: v1
kind: Service
metadata:
  name: grafana # Use this as hostname to communicate with service via HTTP
  namespace: monitoring


spec:
  type: NodePort
  selector:
    name: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000