apiVersion: v1
kind: Service


metadata:
  name: order # Use this as hostname to communicate with service via HTTP


spec:
  selector:
    name: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: order-port