apiVersion: v1
kind: Service
metadata:
  name: payment # Use this as hostname to communicate with service via HTTP


spec:
  selector:
    name: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: payment-port