apiVersion: v1
kind: Service
metadata:
  name: payment # Use this as hostname to communicate with service via HTTP


spec:
  selector:
    app: payment
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 80
    - name: cadvisor
      protocol: TCP
      port: 8080
      targetPort: 8080