apiVersion: v1
kind: Service


metadata:
  namespace: monitoring
  name: prometheus # Use this as hostname to communicate with service via HTTP


spec:
  type: NodePort
  selector:
    name: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: prometheus-port