apiVersion: v1
kind: Service
metadata:
  name: prometheus # Use this as hostname to communicate with service via HTTP
  namespace: monitoring


spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090