apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus


# Allow Prometheus to discover/list all pods and their properties
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'list']