apiVersion: v1
kind: Pod
metadata:
  name: broker-pod
spec:
  containers:
    - name: broker-container
      image: dleclercpro/eda-playground-broker:k8s
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 60
      readinessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 60
  restartPolicy: Never