apiVersion: v1
kind: Pod


metadata:
  name: broker-pod
  labels:
    app.kubernetes.io/name: broker


spec:
  containers:
    - name: broker-container
      image: dleclercpro/eda-playground-broker:k8s
      ports:
        - containerPort: 8000
          name: broker-port
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 60
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 60
  restartPolicy: Always