apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-hpa


spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  
  minReplicas: 1
  maxReplicas: 5

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # % of pod's allocated resource