apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery


spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  strategy:
    type: RollingUpdate

  # Pod
  template:
    metadata:
      labels:
        app: delivery

    spec:
      containers:
        - name: delivery
          image: dleclercpro/eda-playground-delivery:monitoring
          imagePullPolicy: IfNotPresent # To avoid pulling image from repo
          ports:
            - containerPort: 80
              name: delivery-port
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
      restartPolicy: Always