apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring


spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  
  # Pod
  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
      - name: grafana
        image: dleclercpro/eda-playground-grafana:monitoring
        ports:
        - containerPort: 3000