apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring


spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  
  # Pod
  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
        - name: app
          image: dleclercpro/eda-playground-grafana:v2.0.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources # Data sources provisioning directory
            - name: dashboard-providers
              mountPath: /etc/grafana/provisioning/dashboards # Dashboard providers provisioning directory
            - name: dashboard
              mountPath: /var/lib/grafana/dashboards # Dashboard provisioning directory

      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboard-providers
          configMap:
            name: grafana-dashboard-providers
        - name: dashboard
          configMap:
            name: grafana-dashboard