apiVersion: apps/v1
kind: Deployment


metadata:
  name: order-deployment
  labels:
    app.kubernetes.io/name: order


spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order
  strategy:
    type: RollingUpdate

  # Pod
  template:
    metadata:
      # name: order-pod # K8s will use deployment name and a UUID for pod names
      labels:
        app.kubernetes.io/name: order

    spec:
      containers:
        - name: order-container
          image: dleclercpro/eda-playground-order:monitoring
          imagePullPolicy: IfNotPresent # To avoid pulling image from repo
          ports:
            - containerPort: 80
              name: order-port
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
      restartPolicy: Always