apiVersion: apps/v1
kind: Deployment
metadata:
  name: order


spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  strategy:
    type: RollingUpdate

  # Pod
  template:
    metadata:
      labels:
        app: order
      annotations:
        prometheus.io/scrape: 'true'

    spec:
      containers:
        - name: app
          image: dleclercpro/eda-playground-order:v2.0.0
          imagePullPolicy: IfNotPresent # To avoid pulling image from repo
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
        
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.47.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      restartPolicy: Always