apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    name: order


spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  strategy:
    type: RollingUpdate

  # Pod
  template:
    metadata:
      labels:
        app: order

    spec:
      containers:
        - name: order-container
          image: dleclercpro/eda-playground-order:monitoring
          imagePullPolicy: IfNotPresent # To avoid pulling image from repo
          ports:
            - containerPort: 80
              name: order-port
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
      restartPolicy: Always