apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    name: payment


spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment
  strategy:
    type: RollingUpdate

  # Pod
  template:
    metadata:
      labels:
        name: payment

    spec:
      containers:
        - name: payment-container
          image: dleclercpro/eda-playground-payment:monitoring
          imagePullPolicy: IfNotPresent # To avoid pulling image from repo
          ports:
            - containerPort: 80
              name: payment-port
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
      restartPolicy: Always