apiVersion: apps/v1
kind: Deployment


metadata:
  name: payment-deployment
  labels:
    app.kubernetes.io/name: payment


spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: payment
  strategy:
    type: RollingUpdate

  # Pod
  template:
    metadata:
      # name: payment-pod # K8s will use deployment name and a UUID for pod names
      labels:
        app.kubernetes.io/name: payment

    spec:
      containers:
        - name: payment-container
          image: dleclercpro/eda-playground-payment:k8s
          imagePullPolicy: IfNotPresent # To avoid pulling image from repo
          ports:
            - containerPort: 8002
              name: payment-port
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 0
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /ready
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 30
      restartPolicy: Always