apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring


spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  
  # Pod
  template:
    metadata:
      labels:
        app: prometheus

    spec:
      containers:
        - name: prometheus
          image: dleclercpro/eda-playground-prometheus:monitoring
          ports:
            - containerPort: 9090