apiVersion: apps/v1
kind: Deployment


metadata:
  name: prometheus-operator-deployment
  namespace: monitoring


spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-operator
  
  # Pod
  template:
    metadata:
      labels:
        name: prometheus-operator
    spec:
      serviceAccountName: prometheus-operator
      containers:
      - name: prometheus-operator
        image: bitnami/prometheus-operator:latest