# Prometheus server configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s # Re-load rules using this interval


# Rules to be considered
rule_files:
  # - 'first_rules.yml'
  # - 'second_rules.yml'


# Resources to be monitored
scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']
  
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']